/* Autogenerated by png2wx.pl on Tue Apr 16 19:14:35 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_climatology;

#ifdef CLIMATOLOGY_USE_SVG
extern wxString _svg_climatology;
extern wxString _svg_climatology_rollover;
extern wxString _svg_climatology_toggled;
#endif

#endif /* ICONS_H */
