/* Autogenerated by png2wx.pl on Wed Feb 27 17:43:35 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_climatology;

#endif /* ICONS_H */
